"""All domain enums. Stored as native PostgreSQL enum types."""
import enum


class UserRole(str, enum.Enum):
    ADMIN = "ADMIN"
    DATA_OWNER = "DATA_OWNER"
    REVIEWER = "REVIEWER"
    ESG_MANAGER = "ESG_MANAGER"
    MANAGEMENT = "MANAGEMENT"
    ASSESSOR = "ASSESSOR"


class EntityType(str, enum.Enum):
    GROUP = "GROUP"
    SUBSIDIARY = "SUBSIDIARY"
    BUSINESS_UNIT = "BUSINESS_UNIT"
    PLANT = "PLANT"
    PROJECT = "PROJECT"
    DEPARTMENT = "DEPARTMENT"


class MetricDataType(str, enum.Enum):
    NUMERIC = "numeric"
    QUALITATIVE = "qualitative"
    CATEGORICAL = "categorical"
    BOOLEAN = "boolean"


class AggregationSemantics(str, enum.Enum):
    SUM = "SUM"
    WEIGHTED_AVERAGE = "WEIGHTED_AVERAGE"
    RATIO_RECALCULATION = "RATIO_RECALCULATION"
    DERIVED_METRIC = "DERIVED_METRIC"
    DIRECT_VALUE = "DIRECT_VALUE"


class MetricValueStatus(str, enum.Enum):
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    LOCKED = "LOCKED"
    NEEDS_CORRECTION = "NEEDS_CORRECTION"
    REJECTED = "REJECTED"


class AssignmentStatus(str, enum.Enum):
    NOT_STARTED = "NOT_STARTED"
    IN_PROGRESS = "IN_PROGRESS"
    SUBMITTED = "SUBMITTED"
    UNDER_REVIEW = "UNDER_REVIEW"
    APPROVED = "APPROVED"
    LOCKED = "LOCKED"
    NEEDS_CORRECTION = "NEEDS_CORRECTION"
    REJECTED = "REJECTED"


class ValidationSeverity(str, enum.Enum):
    BLOCKING = "BLOCKING"
    WARNING = "WARNING"
    INFO = "INFO"


class ValidationRuleClass(str, enum.Enum):
    REQUIRED_FIELD = "REQUIRED_FIELD"
    RANGE_VALIDATION = "RANGE_VALIDATION"
    UNIT_VALIDATION = "UNIT_VALIDATION"
    TYPE_VALIDATION = "TYPE_VALIDATION"
    DUPLICATE_DETECTION = "DUPLICATE_DETECTION"
    CROSS_FIELD_RECONCILIATION = "CROSS_FIELD_RECONCILIATION"
    CROSS_SECTION_RECONCILIATION = "CROSS_SECTION_RECONCILIATION"
    YOY_VARIANCE = "YOY_VARIANCE"
    EVIDENCE_COMPLETENESS = "EVIDENCE_COMPLETENESS"
    LOGICAL_CONSISTENCY = "LOGICAL_CONSISTENCY"


class ValidationExceptionStatus(str, enum.Enum):
    OPEN = "OPEN"
    EXPLAINED = "EXPLAINED"
    RESOLVED = "RESOLVED"


class AuditAction(str, enum.Enum):
    CREATED = "CREATED"
    UPDATED = "UPDATED"
    SUBMITTED = "SUBMITTED"
    VALIDATED = "VALIDATED"
    EXCEPTION_RAISED = "EXCEPTION_RAISED"
    EXPLANATION_ADDED = "EXPLANATION_ADDED"
    REVIEWED = "REVIEWED"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    LOCKED = "LOCKED"


class JobStatus(str, enum.Enum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"


class NotificationType(str, enum.Enum):
    DUE_SOON = "DUE_SOON"
    DUE_TOMORROW = "DUE_TOMORROW"
    OVERDUE = "OVERDUE"
    RETURNED_FOR_CORRECTION = "RETURNED_FOR_CORRECTION"
    APPROVED = "APPROVED"
    VALIDATION_EXCEPTION = "VALIDATION_EXCEPTION"
    AI_SUGGESTION_READY = "AI_SUGGESTION_READY"
    PERIOD_LOCKED = "PERIOD_LOCKED"


class AISuggestionStatus(str, enum.Enum):
    PENDING = "PENDING"
    ACCEPTED = "ACCEPTED"
    REJECTED = "REJECTED"
    FAILED = "FAILED"
