"""Representative BRSR metric catalogue used by the seed.

NOTE: This is a representative, synthetic catalogue for the MVP/hackathon
demonstration — NOT a legally authoritative reproduction of the current SEBI
BRSR Core indicator list. The architecture is metadata-driven so the catalogue
can be corrected or extended without code changes.

Metric dict keys map 1:1 to MetricDefinition columns.
Unit families follow the canonical-unit plan implemented in Phase 7:
energy -> MWh, water -> kL, waste -> tonne, emissions -> tCO2e,
currency -> INR crore, workforce/headcount -> count.
"""

METRICS: list[dict] = [
    # ---------------- Section A — General disclosures ----------------
    {"code": "A-CIN", "section": "A", "label": "Corporate Identity Number (CIN)",
     "data_type": "qualitative", "required": True, "agg": "DIRECT_VALUE",
     "scope": "entity", "order": 1},
    {"code": "A-LIST-ACTIVITIES", "section": "A", "label": "List of main activities",
     "data_type": "qualitative", "required": True, "agg": "DIRECT_VALUE", "scope": "entity",
     "order": 2},
    {"code": "A-PRODUCTS-SERVICES", "section": "A", "label": "Products / services sold",
     "data_type": "qualitative", "required": True, "agg": "DIRECT_VALUE", "scope": "entity",
     "order": 3},
    {"code": "A-LOCATIONS-COUNT", "section": "A", "label": "Number of locations",
     "data_type": "numeric", "unit_family": "count", "canonical_unit": "count",
     "required": True, "agg": "SUM", "scope": "entity", "order": 4},
    {"code": "A-MARKETS-SERVED", "section": "A", "label": "Markets served (local / national / international)",
     "data_type": "qualitative", "required": True, "agg": "DIRECT_VALUE", "scope": "entity",
     "order": 5},
    {"code": "A-EMPLOYEES-PAYROLL", "section": "A", "label": "Employees on payroll (including differently abled)",
     "data_type": "numeric", "unit_family": "workforce", "canonical_unit": "count",
     "required": True, "agg": "SUM", "scope": "entity", "order": 6, "brsr_core": True},
    {"code": "A-WORKERS-CONTRACT", "section": "A", "label": "Contract / temporary workers",
     "data_type": "numeric", "unit_family": "workforce", "canonical_unit": "count",
     "required": True, "agg": "SUM", "scope": "entity", "order": 7},
    {"code": "A-EMPLOYEES-LEFT", "section": "A", "label": "Employees who left during the period",
     "data_type": "numeric", "unit_family": "workforce", "canonical_unit": "count",
     "required": True, "agg": "SUM", "scope": "entity", "order": 8},
    {"code": "A-REVENUE", "section": "A", "label": "Total turnover / revenue",
     "data_type": "numeric", "unit_family": "currency", "canonical_unit": "INR crore",
     "allowed_units": ["INR", "INR lakh", "INR crore"], "required": True, "agg": "SUM",
     "scope": "entity", "order": 9},

    # ---------------- Section B — Management & process disclosures ----------------
    {"code": "B-POLICIES", "section": "B", "label": "List of policies for NGRBC principles",
     "data_type": "qualitative", "required": True, "agg": "DIRECT_VALUE", "scope": "entity",
     "order": 1},
    {"code": "B-GRIEVANCE-MECH", "section": "B", "label": "Grievance redressal mechanisms",
     "data_type": "qualitative", "required": True, "agg": "DIRECT_VALUE", "scope": "entity",
     "order": 2},
    {"code": "B-CORE-ASSURANCE", "section": "B", "label": "BRSR Core assured? (yes / no / partial)",
     "data_type": "categorical", "required": True, "agg": "DIRECT_VALUE", "scope": "entity",
     "order": 3},

    # ---------------- Section C — Principle 1: Ethics, transparency, accountability ----------------
    {"code": "C-P1-DIRECTOR-TRAINING-PCT", "section": "C", "principle": "P1",
     "label": "% of Board directors trained on ESG / NGRBC",
     "data_type": "numeric", "unit_family": "percent", "canonical_unit": "percent",
     "required": True, "agg": "WEIGHTED_AVERAGE", "scope": "entity", "order": 1},
    {"code": "C-P1-COI-COMPLAINTS", "section": "C", "principle": "P1",
     "label": "Complaints on conflict of interest received",
     "data_type": "numeric", "unit_family": "count", "canonical_unit": "count",
     "required": True, "agg": "SUM", "scope": "entity", "order": 2},
    {"code": "C-P1-FINES-ACB", "section": "C", "principle": "P1",
     "label": "Fines / penalties for anti-competitive or anti-bribery behaviour (INR crore)",
     "data_type": "numeric", "unit_family": "currency", "canonical_unit": "INR crore",
     "allowed_units": ["INR", "INR lakh", "INR crore"],
     "required": True, "agg": "SUM", "scope": "entity", "order": 3},

    # ---------------- Principle 2: Sustainable and safe goods ----------------
    {"code": "C-P2-RD-SPEND", "section": "C", "principle": "P2",
     "label": "R&D expenditure", "data_type": "numeric", "unit_family": "currency",
     "canonical_unit": "INR crore", "allowed_units": ["INR", "INR lakh", "INR crore"],
     "required": True, "agg": "SUM", "scope": "entity", "order": 1},
    {"code": "C-P2-SUSTAINABLE-PRODUCTS", "section": "C", "principle": "P2",
     "label": "Description of products with environmental / social benefits",
     "data_type": "qualitative", "required": False, "agg": "DIRECT_VALUE", "scope": "entity",
     "order": 2},
    {"code": "C-P2-PRODUCT-RECOVERY-PCT", "section": "C", "principle": "P2",
     "label": "% of products and packaging recovered / recycled at end of life",
     "data_type": "numeric", "unit_family": "percent", "canonical_unit": "percent",
     "required": False, "agg": "WEIGHTED_AVERAGE", "scope": "entity", "order": 3},

    # ---------------- Principle 3: Employee wellbeing ----------------
    {"code": "C-P3-LTI-COUNT", "section": "C", "principle": "P3",
     "label": "Lost-time injuries", "data_type": "numeric", "unit_family": "count",
     "canonical_unit": "count", "required": True, "agg": "SUM", "scope": "facility", "order": 1},
    {"code": "C-P3-MANHOURS", "section": "C", "principle": "P3",
     "label": "Total man-hours worked", "data_type": "numeric", "unit_family": "count",
     "canonical_unit": "count", "required": True, "agg": "SUM", "scope": "facility", "order": 2},
    {"code": "C-P3-LTIFR", "section": "C", "principle": "P3",
     "label": "Lost-time injury frequency rate (per million man-hours)",
     "data_type": "numeric", "unit_family": "rate", "canonical_unit": "per_million_manhours",
     "required": True, "agg": "RATIO_RECALCULATION",
     "num": "C-P3-LTI-COUNT", "den": "C-P3-MANHOURS",
     "scope": "facility", "order": 3, "brsr_core": True, "evidence_required": True},
    {"code": "C-P3-ATTRITION", "section": "C", "principle": "P3",
     "label": "Employee attrition rate (%)",
     "data_type": "numeric", "unit_family": "percent", "canonical_unit": "percent",
     "required": True, "agg": "RATIO_RECALCULATION",
     "num": "A-EMPLOYEES-LEFT", "den": "A-EMPLOYEES-PAYROLL",
     "scope": "entity", "order": 4, "brsr_core": True},
    {"code": "C-P3-WORKFORCE-TOTAL", "section": "C", "principle": "P3",
     "label": "Total workforce (employees + workers) stated in Section C",
     "data_type": "numeric", "unit_family": "workforce", "canonical_unit": "count",
     "required": True, "agg": "SUM", "scope": "entity", "order": 5},
    {"code": "C-P3-HEALTH-INS-PCT", "section": "C", "principle": "P3",
     "label": "% of employees covered by health insurance",
     "data_type": "numeric", "unit_family": "percent", "canonical_unit": "percent",
     "required": False, "agg": "WEIGHTED_AVERAGE", "scope": "entity", "order": 6},
    {"code": "C-P3-GRIEVANCES-RESOLVED", "section": "C", "principle": "P3",
     "label": "Employee grievances resolved during the period",
     "data_type": "numeric", "unit_family": "count", "canonical_unit": "count",
     "required": False, "agg": "SUM", "scope": "entity", "order": 7},

    # ---------------- Principle 4: Stakeholder responsiveness ----------------
    {"code": "C-P4-STAKEHOLDER-PCT", "section": "C", "principle": "P4",
     "label": "% of stakeholders identified via stakeholder consultation",
     "data_type": "numeric", "unit_family": "percent", "canonical_unit": "percent",
     "required": False, "agg": "WEIGHTED_AVERAGE", "scope": "entity", "order": 1},
    {"code": "C-P4-GRIEVANCES", "section": "C", "principle": "P4",
     "label": "Stakeholder grievances received",
     "data_type": "numeric", "unit_family": "count", "canonical_unit": "count",
     "required": False, "agg": "SUM", "scope": "entity", "order": 2},

    # ---------------- Principle 5: Human rights ----------------
    {"code": "C-P5-HR-ASSESSED-PCT", "section": "C", "principle": "P5",
     "label": "% of plants / facilities assessed for human-rights risks",
     "data_type": "numeric", "unit_family": "percent", "canonical_unit": "percent",
     "required": False, "agg": "WEIGHTED_AVERAGE", "scope": "entity", "order": 1},
    {"code": "C-P5-CHILD-LABOUR-GRIEVANCES", "section": "C", "principle": "P5",
     "label": "Grievances related to child / forced / involuntary labour",
     "data_type": "numeric", "unit_family": "count", "canonical_unit": "count",
     "required": True, "agg": "SUM", "scope": "entity", "order": 2},

    # ---------------- Principle 6: Environment ----------------
    {"code": "C-P6-GRID-RENEWABLE-MWH", "section": "C", "principle": "P6",
     "label": "Electricity from renewable sources", "data_type": "numeric",
     "unit_family": "energy", "canonical_unit": "MWh",
     "allowed_units": ["kWh", "MWh", "GJ"],
     "required": True, "agg": "SUM", "scope": "facility", "order": 1},
    {"code": "C-P6-GRID-NONRENEWABLE-MWH", "section": "C", "principle": "P6",
     "label": "Electricity from non-renewable sources", "data_type": "numeric",
     "unit_family": "energy", "canonical_unit": "MWh",
     "allowed_units": ["kWh", "MWh", "GJ"],
     "required": True, "agg": "SUM", "scope": "facility", "order": 2},
    {"code": "C-P6-DIESEL-LITRES", "section": "C", "principle": "P6",
     "label": "Diesel consumption", "data_type": "numeric", "unit_family": "fuel_volume",
     "canonical_unit": "litre", "allowed_units": ["litre", "kL"],
     "required": True, "agg": "SUM", "scope": "facility", "order": 3},
    {"code": "C-P6-TOTAL-ENERGY", "section": "C", "principle": "P6",
     "label": "Total energy consumption", "data_type": "numeric", "unit_family": "energy",
     "canonical_unit": "MWh", "allowed_units": ["kWh", "MWh", "GJ"],
     "required": True, "agg": "SUM", "scope": "facility", "order": 4,
     "formula": "F-TOTAL-ENERGY", "brsr_core": True, "evidence_required": True},
    {"code": "C-P6-RENEWABLE-SHARE", "section": "C", "principle": "P6",
     "label": "Renewable energy share of total consumption (%)",
     "data_type": "numeric", "unit_family": "percent", "canonical_unit": "percent",
     "required": False, "agg": "RATIO_RECALCULATION",
     "num": "C-P6-GRID-RENEWABLE-MWH", "den": "C-P6-TOTAL-ENERGY",
     "scope": "entity", "order": 5, "brsr_core": True},
    {"code": "C-P6-SCOPE1-TCO2E", "section": "C", "principle": "P6",
     "label": "GHG emissions — Scope 1 (tCO2e)", "data_type": "numeric",
     "unit_family": "emissions", "canonical_unit": "tCO2e",
     "allowed_units": ["kg CO2e", "tCO2e"],
     "required": True, "agg": "SUM", "scope": "facility", "order": 6,
     "formula": "F-SCOPE1", "brsr_core": True, "evidence_required": True},
    {"code": "C-P6-SCOPE2-TCO2E", "section": "C", "principle": "P6",
     "label": "GHG emissions — Scope 2 (tCO2e)", "data_type": "numeric",
     "unit_family": "emissions", "canonical_unit": "tCO2e",
     "allowed_units": ["kg CO2e", "tCO2e"],
     "required": True, "agg": "SUM", "scope": "facility", "order": 7,
     "brsr_core": True, "evidence_required": True},
    {"code": "C-P6-TOTAL-GHG", "section": "C", "principle": "P6",
     "label": "Total GHG emissions (Scope 1 + Scope 2, tCO2e)", "data_type": "numeric",
     "unit_family": "emissions", "canonical_unit": "tCO2e",
     "required": True, "agg": "SUM", "scope": "entity", "order": 8,
     "formula": "F-TOTAL-GHG", "brsr_core": True},
    {"code": "C-P6-GHG-INTENSITY", "section": "C", "principle": "P6",
     "label": "GHG intensity per revenue (tCO2e / INR crore)",
     "data_type": "numeric", "unit_family": "intensity", "canonical_unit": "tCO2e_per_crore",
     "required": True, "agg": "RATIO_RECALCULATION",
     "num": "C-P6-TOTAL-GHG", "den": "A-REVENUE",
     "scope": "entity", "order": 9, "brsr_core": True},
    {"code": "C-P6-ENERGY-INTENSITY", "section": "C", "principle": "P6",
     "label": "Energy intensity per revenue (MWh / INR crore)",
     "data_type": "numeric", "unit_family": "intensity", "canonical_unit": "MWh_per_crore",
     "required": True, "agg": "RATIO_RECALCULATION",
     "num": "C-P6-TOTAL-ENERGY", "den": "A-REVENUE",
     "scope": "entity", "order": 10, "brsr_core": True},
    {"code": "C-P6-WATER-WITHDRAWAL", "section": "C", "principle": "P6",
     "label": "Total water withdrawal", "data_type": "numeric", "unit_family": "water",
     "canonical_unit": "kL", "allowed_units": ["litre", "kL", "ML"],
     "required": True, "agg": "SUM", "scope": "facility", "order": 11,
     "brsr_core": True, "evidence_required": True},
    {"code": "C-P6-WATER-DISCHARGE", "section": "C", "principle": "P6",
     "label": "Total water discharge", "data_type": "numeric", "unit_family": "water",
     "canonical_unit": "kL", "allowed_units": ["litre", "kL", "ML"],
     "required": True, "agg": "SUM", "scope": "facility", "order": 12},
    {"code": "C-P6-WATER-CONSUMPTION", "section": "C", "principle": "P6",
     "label": "Total water consumption", "data_type": "numeric", "unit_family": "water",
     "canonical_unit": "kL", "allowed_units": ["litre", "kL", "ML"],
     "required": True, "agg": "SUM", "scope": "facility", "order": 13,
     "brsr_core": True},
    {"code": "C-P6-WATER-INTENSITY", "section": "C", "principle": "P6",
     "label": "Water intensity per revenue (kL / INR crore)",
     "data_type": "numeric", "unit_family": "intensity", "canonical_unit": "kL_per_crore",
     "required": True, "agg": "RATIO_RECALCULATION",
     "num": "C-P6-WATER-WITHDRAWAL", "den": "A-REVENUE",
     "scope": "entity", "order": 14, "brsr_core": True},
    {"code": "C-P6-WASTE-GENERATED", "section": "C", "principle": "P6",
     "label": "Total waste generated", "data_type": "numeric", "unit_family": "waste",
     "canonical_unit": "tonne", "allowed_units": ["kg", "tonne"],
     "required": True, "agg": "SUM", "scope": "facility", "order": 15,
     "brsr_core": True, "evidence_required": True},
    {"code": "C-P6-WASTE-RECYCLED", "section": "C", "principle": "P6",
     "label": "Waste recycled / reused", "data_type": "numeric", "unit_family": "waste",
     "canonical_unit": "tonne", "allowed_units": ["kg", "tonne"],
     "required": False, "agg": "SUM", "scope": "facility", "order": 16},
    {"code": "C-P6-WASTE-RECYCLED-PCT", "section": "C", "principle": "P6",
     "label": "% waste recycled or reused", "data_type": "numeric", "unit_family": "percent",
     "canonical_unit": "percent", "required": False, "agg": "RATIO_RECALCULATION",
     "num": "C-P6-WASTE-RECYCLED", "den": "C-P6-WASTE-GENERATED",
     "scope": "entity", "order": 17},
    {"code": "C-P6-ENV-FINES", "section": "C", "principle": "P6",
     "label": "Fines / penalties for environmental non-compliance (INR crore)",
     "data_type": "numeric", "unit_family": "currency", "canonical_unit": "INR crore",
     "allowed_units": ["INR", "INR lakh", "INR crore"],
     "required": True, "agg": "SUM", "scope": "entity", "order": 18},

    # ---------------- Principle 7: Responsible policy advocacy ----------------
    {"code": "C-P7-POLICY-ENGAGE-PCT", "section": "C", "principle": "P7",
     "label": "% of subsidiaries engaged with public policy bodies",
     "data_type": "numeric", "unit_family": "percent", "canonical_unit": "percent",
     "required": False, "agg": "WEIGHTED_AVERAGE", "scope": "entity", "order": 1},
    {"code": "C-P7-ANTI-COMPETITIVE-ACTIONS", "section": "C", "principle": "P7",
     "label": "Actions brought against the entity for anti-competitive behaviour",
     "data_type": "numeric", "unit_family": "count", "canonical_unit": "count",
     "required": True, "agg": "SUM", "scope": "entity", "order": 2},

    # ---------------- Principle 8: Inclusive growth ----------------
    {"code": "C-P8-CSR-SPEND", "section": "C", "principle": "P8",
     "label": "Amount spent on CSR (INR crore)", "data_type": "numeric",
     "unit_family": "currency", "canonical_unit": "INR crore",
     "allowed_units": ["INR", "INR lakh", "INR crore"],
     "required": True, "agg": "SUM", "scope": "entity", "order": 1,
     "brsr_core": True, "evidence_required": True},
    {"code": "C-P8-SME-PROCUREMENT-PCT", "section": "C", "principle": "P8",
     "label": "% procurement from small and medium producers",
     "data_type": "numeric", "unit_family": "percent", "canonical_unit": "percent",
     "required": False, "agg": "WEIGHTED_AVERAGE", "scope": "entity", "order": 2},
    {"code": "C-P8-BENEFICIARIES", "section": "C", "principle": "P8",
     "label": "Beneficiaries of CSR / development initiatives",
     "data_type": "numeric", "unit_family": "count", "canonical_unit": "count",
     "required": False, "agg": "SUM", "scope": "entity", "order": 3},

    # ---------------- Principle 9: Consumer value ----------------
    {"code": "C-P9-DATA-BREACHES", "section": "C", "principle": "P9",
     "label": "Data breaches involving personally identifiable information",
     "data_type": "numeric", "unit_family": "count", "canonical_unit": "count",
     "required": True, "agg": "SUM", "scope": "entity", "order": 1,
     "brsr_core": True, "evidence_required": True},
    {"code": "C-P9-COMPLAINTS", "section": "C", "principle": "P9",
     "label": "Consumer complaints received", "data_type": "numeric", "unit_family": "count",
     "canonical_unit": "count", "required": True, "agg": "SUM", "scope": "entity", "order": 2},
    {"code": "C-P9-COMPLAINTS-RESOLVED-PCT", "section": "C", "principle": "P9",
     "label": "% of consumer complaints resolved", "data_type": "numeric",
     "unit_family": "percent", "canonical_unit": "percent", "required": False,
     "agg": "RATIO_RECALCULATION",
     "num": "C-P9-GRIEVANCES-RESOLVED", "den": "C-P9-COMPLAINTS",
     "scope": "entity", "order": 3},
    {"code": "C-P9-GRIEVANCES-RESOLVED", "section": "C", "principle": "P9",
     "label": "Consumer grievances resolved", "data_type": "numeric", "unit_family": "count",
     "canonical_unit": "count", "required": False, "agg": "SUM", "scope": "entity", "order": 4},
    {"code": "C-P9-CYBERSECURITY-CERT", "section": "C", "principle": "P9",
     "label": "Cybersecurity certifications held", "data_type": "qualitative",
     "required": False, "agg": "DIRECT_VALUE", "scope": "entity", "order": 5},
]

# Metric codes present in the previous framework version (FY2024-25).
# Renamed / redefined codes demonstrate cross-version lineage mapping.
PREVIOUS_VERSION_CODES = [
    "A-EMPLOYEES-PAYROLL", "A-EMPLOYEES-LEFT", "A-REVENUE", "A-LOCATIONS-COUNT",
    "C-P3-LTIFR", "C-P3-LTI-COUNT", "C-P3-MANHOURS", "C-P3-ATTRITION",
    "C-P3-WORKFORCE-TOTAL",
    "C-P6-GRID-RENEWABLE-MWH", "C-P6-GRID-NONRENEWABLE-MWH", "C-P6-DIESEL-LITRES",
    "C-P6-TOTAL-ENERGY", "C-P6-SCOPE1-TCO2E", "C-P6-SCOPE2-TCO2E", "C-P6-TOTAL-GHG",
    "C-P6-GHG-INTENSITY", "C-P6-ENERGY-INTENSITY",
    "C-P6-WATER-WITHDRAWAL", "C-P6-WATER-CONSUMPTION",
    "C-P6-WASTE-GENERATED", "C-P8-CSR-SPEND", "C-P9-DATA-BREACHES",
    "C-P9-COMPLAINTS",
]

# Codes renamed between versions: old code -> (new code, mapping type)
RENAMES = {
    "C-P6-WATER-USED": ("C-P6-WATER-WITHDRAWAL", "REDEFINED"),
}

FORMULAS: list[dict] = [
    {"code": "F-TOTAL-ENERGY", "name": "Total energy consumption",
     "expression": "C-P6-GRID-RENEWABLE-MWH + C-P6-GRID-NONRENEWABLE-MWH",
     "inputs": ["C-P6-GRID-RENEWABLE-MWH", "C-P6-GRID-NONRENEWABLE-MWH"],
     "constants": {},
     "description": "Sum of renewable and non-renewable grid electricity (MWh)."},
    {"code": "F-SCOPE1", "name": "Scope 1 emissions from diesel",
     "expression": "C-P6-DIESEL-LITRES * DIESEL_EF_KG_PER_LITRE / 1000",
     "inputs": ["C-P6-DIESEL-LITRES"],
     "constants": {"DIESEL_EF_KG_PER_LITRE": 2.68},
     "description": "Diesel litres x 2.68 kgCO2e/litre, converted to tCO2e."},
    {"code": "F-TOTAL-GHG", "name": "Total GHG (Scope 1 + Scope 2)",
     "expression": "C-P6-SCOPE1-TCO2E + C-P6-SCOPE2-TCO2E",
     "inputs": ["C-P6-SCOPE1-TCO2E", "C-P6-SCOPE2-TCO2E"],
     "constants": {},
     "description": "Sum of Scope 1 and Scope 2 emissions."},
]

VALIDATION_RULES: list[dict] = [
    {"code": "VR-REQ-CORE", "class": "REQUIRED_FIELD", "target": None,
     "severity": "BLOCKING", "applies_on": "submit",
     "config": {"scope": "brsr_core"},
     "message": "BRSR Core metric is required but has no value"},
    {"code": "VR-RANGE-ATTRITION", "class": "RANGE_VALIDATION", "target": "C-P3-ATTRITION",
     "severity": "BLOCKING", "applies_on": "submit",
     "config": {"min": 0, "max": 100},
     "message": "Attrition rate must be between 0 and 100 percent"},
    {"code": "VR-RANGE-PERCENT", "class": "RANGE_VALIDATION", "target": None,
     "severity": "WARNING", "applies_on": "submit",
     "config": {"scope": "unit_family:percent", "min": 0, "max": 200},
     "message": "Percent metric outside plausible range 0-200"},
    {"code": "VR-UNIT", "class": "UNIT_VALIDATION", "target": None,
     "severity": "BLOCKING", "applies_on": "submit",
     "config": {"scope": "all_numeric"},
     "message": "Unit is not in the metric's allowed units"},
    {"code": "VR-TYPE", "class": "TYPE_VALIDATION", "target": None,
     "severity": "BLOCKING", "applies_on": "submit",
     "config": {"scope": "all"},
     "message": "Value type does not match the metric data type"},
    {"code": "VR-DUP", "class": "DUPLICATE_DETECTION", "target": None,
     "severity": "INFO", "applies_on": "review",
     "config": {"scope": "same_period_entity"},
     "message": "Identical value submitted more than once for the same entity/period"},
    {"code": "VR-XF-EMPLOYEES", "class": "CROSS_FIELD_RECONCILIATION",
     "target": "A-EMPLOYEES-PAYROLL", "severity": "BLOCKING", "applies_on": "review",
     "config": {"cross_metric_code": "C-P3-WORKFORCE-TOTAL", "tolerance": 0},
     "message": "Section A employee count does not reconcile with Section C workforce"},
    {"code": "VR-XS-EMPLOYEES", "class": "CROSS_SECTION_RECONCILIATION",
     "target": "A-EMPLOYEES-PAYROLL", "severity": "BLOCKING", "applies_on": "review",
     "config": {"cross_section": "C", "cross_metric_code": "C-P3-WORKFORCE-TOTAL",
                "tolerance": 0},
     "message": "Section A employee count differs from Section C workforce disclosure"},
    {"code": "VR-YOY-ENERGY", "class": "YOY_VARIANCE", "target": "C-P6-TOTAL-ENERGY",
     "severity": "WARNING", "applies_on": "review",
     "config": {"threshold_percent_from_env": True},
     "message": "Total energy consumption changed by more than the year-on-year threshold"},
    {"code": "VR-EVIDENCE-CORE", "class": "EVIDENCE_COMPLETENESS", "target": None,
     "severity": "BLOCKING", "applies_on": "review",
     "config": {"scope": "brsr_core"},
     "message": "BRSR Core metric is missing required evidence"},
    {"code": "VR-LOGIC-WATER", "class": "LOGICAL_CONSISTENCY",
     "target": "C-P6-WATER-WITHDRAWAL", "severity": "WARNING", "applies_on": "review",
     "config": {"condition": "nonzero_discharge_requires_nonzero_withdrawal"},
     "message": "Water discharge is non-zero while withdrawal is zero"},
]
