"""phase 2 initial schema

Revision ID: fc6d8c4e4389
Revises: 
Create Date: 2026-09-27 14:17:09.917142
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy.dialects.postgresql as pg
from sqlalchemy.dialects import postgresql

revision: str = 'fc6d8c4e4389'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'DATA_OWNER', 'REVIEWER', 'ESG_MANAGER', 'MANAGEMENT', 'ASSESSOR', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_user')),
    sa.UniqueConstraint('email', name=op.f('uq_app_user_email'))
    )
    op.create_table('entity',
    sa.Column('parent_id', sa.Uuid(), nullable=True),
    sa.Column('entity_type', sa.Enum('GROUP', 'SUBSIDIARY', 'BUSINESS_UNIT', 'PLANT', 'PROJECT', 'DEPARTMENT', name='entity_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('reporting_boundary_notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('effective_to IS NULL OR effective_to >= effective_from', name=op.f('ck_entity_effective_dates_ordered')),
    sa.ForeignKeyConstraint(['parent_id'], ['entity.id'], name=op.f('fk_entity_parent_id_entity'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity'))
    )
    op.create_index('ix_entity_parent_id', 'entity', ['parent_id'], unique=False)
    op.create_table('framework_version',
    sa.Column('version_code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_framework_version')),
    sa.UniqueConstraint('version_code', name=op.f('uq_framework_version_version_code'))
    )
    op.create_table('audit_event',
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('actor_label', sa.String(length=255), nullable=False),
    sa.Column('action', sa.Enum('CREATED', 'UPDATED', 'SUBMITTED', 'VALIDATED', 'EXCEPTION_RAISED', 'EXPLANATION_ADDED', 'REVIEWED', 'APPROVED', 'REJECTED', 'LOCKED', name='audit_action'), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=True),
    sa.Column('metric_code', sa.String(length=100), nullable=True),
    sa.Column('object_type', sa.String(length=100), nullable=False),
    sa.Column('object_id', sa.String(length=64), nullable=True),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('evidence_reference', sa.String(length=64), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['app_user.id'], name=op.f('fk_audit_event_actor_id_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_event'))
    )
    op.create_index('ix_audit_event_created', 'audit_event', ['created_at'], unique=False)
    op.create_index('ix_audit_event_entity', 'audit_event', ['entity_id'], unique=False)
    op.create_index('ix_audit_event_object', 'audit_event', ['object_type', 'object_id'], unique=False)
    op.create_table('formula_definition',
    sa.Column('framework_version_id', sa.Uuid(), nullable=False),
    sa.Column('code', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['framework_version_id'], ['framework_version.id'], name=op.f('fk_formula_definition_framework_version_id_framework_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_formula_definition')),
    sa.UniqueConstraint('framework_version_id', 'code', name=op.f('uq_formula_definition_framework_version_id'))
    )
    op.create_table('metric_lineage',
    sa.Column('from_framework_version_id', sa.Uuid(), nullable=False),
    sa.Column('from_metric_code', sa.String(length=100), nullable=False),
    sa.Column('to_framework_version_id', sa.Uuid(), nullable=False),
    sa.Column('to_metric_code', sa.String(length=100), nullable=False),
    sa.Column('mapping_type', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['from_framework_version_id'], ['framework_version.id'], name=op.f('fk_metric_lineage_from_framework_version_id_framework_version'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['to_framework_version_id'], ['framework_version.id'], name=op.f('fk_metric_lineage_to_framework_version_id_framework_version'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_lineage')),
    sa.UniqueConstraint('from_framework_version_id', 'from_metric_code', 'to_framework_version_id', 'to_metric_code', name=op.f('uq_metric_lineage_from_framework_version_id'))
    )
    op.create_table('notification',
    sa.Column('recipient_user_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('DUE_SOON', 'DUE_TOMORROW', 'OVERDUE', 'RETURNED_FOR_CORRECTION', 'APPROVED', 'VALIDATION_EXCEPTION', 'AI_SUGGESTION_READY', 'PERIOD_LOCKED', name='notification_type'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['recipient_user_id'], ['app_user.id'], name=op.f('fk_notification_recipient_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notification'))
    )
    op.create_index('ix_notification_recipient', 'notification', ['recipient_user_id', 'read_at'], unique=False)
    op.create_table('reporting_period',
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('framework_version_id', sa.Uuid(), nullable=False),
    sa.Column('locked', sa.Boolean(), nullable=False),
    sa.Column('locked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('locked_by', sa.Uuid(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_reporting_period_dates_ordered')),
    sa.ForeignKeyConstraint(['framework_version_id'], ['framework_version.id'], name=op.f('fk_reporting_period_framework_version_id_framework_version'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['locked_by'], ['app_user.id'], name=op.f('fk_reporting_period_locked_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_reporting_period')),
    sa.UniqueConstraint('label', name=op.f('uq_reporting_period_label'))
    )
    op.create_table('user_entity_scope',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_user_entity_scope_entity_id_entity'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], name=op.f('fk_user_entity_scope_user_id_app_user'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_entity_scope')),
    sa.UniqueConstraint('user_id', 'entity_id', name=op.f('uq_user_entity_scope_user_id'))
    )
    op.create_table('validation_rule',
    sa.Column('framework_version_id', sa.Uuid(), nullable=False),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_class', sa.Enum('REQUIRED_FIELD', 'RANGE_VALIDATION', 'UNIT_VALIDATION', 'TYPE_VALIDATION', 'DUPLICATE_DETECTION', 'CROSS_FIELD_RECONCILIATION', 'CROSS_SECTION_RECONCILIATION', 'YOY_VARIANCE', 'EVIDENCE_COMPLETENESS', 'LOGICAL_CONSISTENCY', name='validation_rule_class'), nullable=False),
    sa.Column('target_metric_code', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.Enum('BLOCKING', 'WARNING', 'INFO', name='validation_severity'), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('applies_on', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('message_template', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['framework_version_id'], ['framework_version.id'], name=op.f('fk_validation_rule_framework_version_id_framework_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_rule')),
    sa.UniqueConstraint('framework_version_id', 'rule_code', 'version', name=op.f('uq_validation_rule_framework_version_id'))
    )
    op.create_index('ix_validation_rule_target', 'validation_rule', ['framework_version_id', 'target_metric_code'], unique=False)
    op.create_table('assignment',
    sa.Column('metric_code', sa.String(length=100), nullable=False),
    sa.Column('framework_version_id', sa.Uuid(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('owner_user_id', sa.Uuid(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'IN_PROGRESS', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'LOCKED', 'NEEDS_CORRECTION', 'REJECTED', name='assignment_status'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_assignment_created_by_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_assignment_entity_id_entity'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['framework_version_id'], ['framework_version.id'], name=op.f('fk_assignment_framework_version_id_framework_version'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_user_id'], ['app_user.id'], name=op.f('fk_assignment_owner_user_id_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_period.id'], name=op.f('fk_assignment_period_id_reporting_period'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_assignment')),
    sa.UniqueConstraint('metric_code', 'entity_id', 'period_id', name=op.f('uq_assignment_metric_code'))
    )
    op.create_index('ix_assignment_owner', 'assignment', ['owner_user_id'], unique=False)
    op.create_index('ix_assignment_period_status', 'assignment', ['period_id', 'status'], unique=False)
    op.create_table('bulk_import_job',
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('file_object_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='job_status'), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows', sa.Integer(), nullable=False),
    sa.Column('invalid_rows', sa.Integer(), nullable=False),
    sa.Column('error_report_object_key', sa.String(length=500), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_period.id'], name=op.f('fk_bulk_import_job_period_id_reporting_period'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.id'], name=op.f('fk_bulk_import_job_uploaded_by_app_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_bulk_import_job'))
    )
    op.create_index('ix_bulk_import_job_uploader', 'bulk_import_job', ['uploaded_by'], unique=False)
    op.create_table('formula_version',
    sa.Column('formula_definition_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('expression', sa.Text(), nullable=False),
    sa.Column('input_metric_codes', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('constants', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_formula_version_version_positive')),
    sa.ForeignKeyConstraint(['formula_definition_id'], ['formula_definition.id'], name=op.f('fk_formula_version_formula_definition_id_formula_definition'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_formula_version')),
    sa.UniqueConstraint('formula_definition_id', 'version', name=op.f('uq_formula_version_formula_definition_id'))
    )
    op.create_table('metric_definition',
    sa.Column('framework_version_id', sa.Uuid(), nullable=False),
    sa.Column('metric_code', sa.String(length=100), nullable=False),
    sa.Column('question_code', sa.String(length=50), nullable=True),
    sa.Column('section', sa.String(length=1), nullable=False),
    sa.Column('principle', sa.String(length=2), nullable=True),
    sa.Column('label', sa.String(length=500), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.Enum('NUMERIC', 'QUALITATIVE', 'CATEGORICAL', 'BOOLEAN', name='metric_data_type'), nullable=False),
    sa.Column('unit_family', sa.String(length=50), nullable=True),
    sa.Column('allowed_units', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('canonical_unit', sa.String(length=50), nullable=True),
    sa.Column('scope', sa.String(length=100), nullable=True),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('applicability_rule', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('aggregation_semantics', sa.Enum('SUM', 'WEIGHTED_AVERAGE', 'RATIO_RECALCULATION', 'DERIVED_METRIC', 'DIRECT_VALUE', name='aggregation_semantics'), nullable=False),
    sa.Column('ratio_numerator_code', sa.String(length=100), nullable=True),
    sa.Column('ratio_denominator_code', sa.String(length=100), nullable=True),
    sa.Column('calculation_rule_id', sa.Uuid(), nullable=True),
    sa.Column('evidence_required', sa.Boolean(), nullable=False),
    sa.Column('brsr_core', sa.Boolean(), nullable=False),
    sa.Column('source_reference', sa.String(length=255), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.CheckConstraint("aggregation_semantics <> 'RATIO_RECALCULATION' OR (ratio_numerator_code IS NOT NULL AND ratio_denominator_code IS NOT NULL)", name=op.f('ck_metric_definition_ratio_requires_numerator_denominator')),
    sa.CheckConstraint("section <> 'C' OR principle IS NOT NULL", name=op.f('ck_metric_definition_section_c_requires_principle')),
    sa.CheckConstraint("section IN ('A', 'B', 'C')", name=op.f('ck_metric_definition_section_valid')),
    sa.CheckConstraint('display_order IS NULL OR display_order >= 0', name=op.f('ck_metric_definition_display_order_valid')),
    sa.ForeignKeyConstraint(['calculation_rule_id'], ['formula_definition.id'], name=op.f('fk_metric_definition_calculation_rule_id_formula_definition'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['framework_version_id'], ['framework_version.id'], name=op.f('fk_metric_definition_framework_version_id_framework_version'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_definition')),
    sa.UniqueConstraint('framework_version_id', 'metric_code', name=op.f('uq_metric_definition_framework_version_id'))
    )
    op.create_table('report_snapshot',
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('framework_version_id', sa.Uuid(), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('checksum IS NOT NULL', name=op.f('ck_report_snapshot_checksum_present')),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_report_snapshot_created_by_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['framework_version_id'], ['framework_version.id'], name=op.f('fk_report_snapshot_framework_version_id_framework_version'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_period.id'], name=op.f('fk_report_snapshot_period_id_reporting_period'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_snapshot')),
    sa.UniqueConstraint('period_id', name=op.f('uq_report_snapshot_period_id'))
    )
    op.create_table('generated_report',
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('file_format', sa.String(length=10), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'SUCCESS', 'FAILED', name='job_status'), nullable=False),
    sa.Column('file_object_key', sa.String(length=500), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_generated_report_created_by_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_period.id'], name=op.f('fk_generated_report_period_id_reporting_period'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['report_snapshot.id'], name=op.f('fk_generated_report_snapshot_id_report_snapshot'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_generated_report'))
    )
    op.create_index('ix_generated_report_period', 'generated_report', ['period_id'], unique=False)
    op.create_table('metric_value',
    sa.Column('assignment_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('raw_value', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('raw_unit', sa.String(length=50), nullable=True),
    sa.Column('normalized_value', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('normalized_unit', sa.String(length=50), nullable=True),
    sa.Column('qualitative_value', sa.Text(), nullable=True),
    sa.Column('is_derived', sa.Boolean(), nullable=False),
    sa.Column('is_calculated', sa.Boolean(), nullable=False),
    sa.Column('formula_id', sa.Uuid(), nullable=True),
    sa.Column('formula_version', sa.Integer(), nullable=True),
    sa.Column('formula_inputs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'UNDER_REVIEW', 'APPROVED', 'LOCKED', 'NEEDS_CORRECTION', 'REJECTED', name='metric_value_status'), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=False),
    sa.Column('submitted_by', sa.Uuid(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.CheckConstraint('version >= 1', name=op.f('ck_metric_value_version_positive')),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], name=op.f('fk_metric_value_assignment_id_assignment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['app_user.id'], name=op.f('fk_metric_value_created_by_app_user'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['formula_id'], ['formula_definition.id'], name=op.f('fk_metric_value_formula_id_formula_definition'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submitted_by'], ['app_user.id'], name=op.f('fk_metric_value_submitted_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_value')),
    sa.UniqueConstraint('assignment_id', 'version', name=op.f('uq_metric_value_assignment_id'))
    )
    op.create_index('ix_metric_value_assignment', 'metric_value', ['assignment_id'], unique=False)
    op.create_table('consolidation_trace',
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('metric_code', sa.String(length=100), nullable=False),
    sa.Column('period_id', sa.Uuid(), nullable=False),
    sa.Column('value_id', sa.Uuid(), nullable=True),
    sa.Column('computed_value', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('contributing_value_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('aggregation_semantics', sa.String(length=30), nullable=True),
    sa.Column('is_stale', sa.Boolean(), nullable=False),
    sa.Column('stale_reason', sa.String(length=255), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_consolidation_trace_entity_id_entity'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_period.id'], name=op.f('fk_consolidation_trace_period_id_reporting_period'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['value_id'], ['metric_value.id'], name=op.f('fk_consolidation_trace_value_id_metric_value'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_consolidation_trace')),
    sa.UniqueConstraint('entity_id', 'metric_code', 'period_id', name=op.f('uq_consolidation_trace_entity_id'))
    )
    op.create_index('ix_consolidation_trace_period', 'consolidation_trace', ['period_id'], unique=False)
    op.create_table('evidence',
    sa.Column('metric_value_id', sa.Uuid(), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('sha256_hash', sa.String(length=64), nullable=False),
    sa.Column('uploaded_by', sa.Uuid(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['metric_value_id'], ['metric_value.id'], name=op.f('fk_evidence_metric_value_id_metric_value'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app_user.id'], name=op.f('fk_evidence_uploaded_by_app_user'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence'))
    )
    op.create_index('ix_evidence_metric_value', 'evidence', ['metric_value_id'], unique=False)
    op.create_index('ix_evidence_sha256', 'evidence', ['sha256_hash'], unique=False)
    op.create_table('validation_exception',
    sa.Column('rule_id', sa.Uuid(), nullable=True),
    sa.Column('rule_code', sa.String(length=100), nullable=False),
    sa.Column('rule_version', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Enum('BLOCKING', 'WARNING', 'INFO', name='validation_severity'), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=False),
    sa.Column('metric_code', sa.String(length=100), nullable=True),
    sa.Column('period_id', sa.Uuid(), nullable=True),
    sa.Column('assignment_id', sa.Uuid(), nullable=True),
    sa.Column('metric_value_id', sa.Uuid(), nullable=True),
    sa.Column('observed_value', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'EXPLAINED', 'RESOLVED', name='validation_exception_status'), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=True),
    sa.Column('explained_by', sa.Uuid(), nullable=True),
    sa.Column('explained_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolved_by', sa.Uuid(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['assignment_id'], ['assignment.id'], name=op.f('fk_validation_exception_assignment_id_assignment'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['entity_id'], ['entity.id'], name=op.f('fk_validation_exception_entity_id_entity'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['explained_by'], ['app_user.id'], name=op.f('fk_validation_exception_explained_by_app_user')),
    sa.ForeignKeyConstraint(['metric_value_id'], ['metric_value.id'], name=op.f('fk_validation_exception_metric_value_id_metric_value'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['period_id'], ['reporting_period.id'], name=op.f('fk_validation_exception_period_id_reporting_period'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['resolved_by'], ['app_user.id'], name=op.f('fk_validation_exception_resolved_by_app_user')),
    sa.ForeignKeyConstraint(['rule_id'], ['validation_rule.id'], name=op.f('fk_validation_exception_rule_id_validation_rule'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_validation_exception'))
    )
    op.create_index('ix_validation_exception_period_status', 'validation_exception', ['period_id', 'status'], unique=False)
    op.create_index('ix_validation_exception_value', 'validation_exception', ['metric_value_id'], unique=False)
    op.create_table('ai_suggestion',
    sa.Column('evidence_id', sa.Uuid(), nullable=False),
    sa.Column('metric_code', sa.String(length=100), nullable=True),
    sa.Column('candidate_value', sa.Numeric(precision=28, scale=8), nullable=True),
    sa.Column('candidate_unit', sa.String(length=50), nullable=True),
    sa.Column('candidate_text', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', 'FAILED', name='ai_suggestion_status'), nullable=False),
    sa.Column('reviewed_by', sa.Uuid(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['evidence_id'], ['evidence.id'], name=op.f('fk_ai_suggestion_evidence_id_evidence'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reviewed_by'], ['app_user.id'], name=op.f('fk_ai_suggestion_reviewed_by_app_user')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ai_suggestion'))
    )
    op.create_index('ix_ai_suggestion_evidence', 'ai_suggestion', ['evidence_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_ai_suggestion_evidence', table_name='ai_suggestion')
    op.drop_table('ai_suggestion')
    op.drop_index('ix_validation_exception_value', table_name='validation_exception')
    op.drop_index('ix_validation_exception_period_status', table_name='validation_exception')
    op.drop_table('validation_exception')
    op.drop_index('ix_evidence_sha256', table_name='evidence')
    op.drop_index('ix_evidence_metric_value', table_name='evidence')
    op.drop_table('evidence')
    op.drop_index('ix_consolidation_trace_period', table_name='consolidation_trace')
    op.drop_table('consolidation_trace')
    op.drop_index('ix_metric_value_assignment', table_name='metric_value')
    op.drop_table('metric_value')
    op.drop_index('ix_generated_report_period', table_name='generated_report')
    op.drop_table('generated_report')
    op.drop_table('report_snapshot')
    op.drop_table('metric_definition')
    op.drop_table('formula_version')
    op.drop_index('ix_bulk_import_job_uploader', table_name='bulk_import_job')
    op.drop_table('bulk_import_job')
    op.drop_index('ix_assignment_period_status', table_name='assignment')
    op.drop_index('ix_assignment_owner', table_name='assignment')
    op.drop_table('assignment')
    op.drop_index('ix_validation_rule_target', table_name='validation_rule')
    op.drop_table('validation_rule')
    op.drop_table('user_entity_scope')
    op.drop_table('reporting_period')
    op.drop_index('ix_notification_recipient', table_name='notification')
    op.drop_table('notification')
    op.drop_table('metric_lineage')
    op.drop_table('formula_definition')
    op.drop_index('ix_audit_event_object', table_name='audit_event')
    op.drop_index('ix_audit_event_entity', table_name='audit_event')
    op.drop_index('ix_audit_event_created', table_name='audit_event')
    op.drop_table('audit_event')
    op.drop_table('framework_version')
    op.drop_index('ix_entity_parent_id', table_name='entity')
    op.drop_table('entity')
    op.drop_table('app_user')
    # ### end Alembic commands ###
    # ### enum types (autogenerate does not emit these) ###
    op.execute('DROP TYPE IF EXISTS aggregation_semantics')
    op.execute('DROP TYPE IF EXISTS ai_suggestion_status')
    op.execute('DROP TYPE IF EXISTS assignment_status')
    op.execute('DROP TYPE IF EXISTS audit_action')
    op.execute('DROP TYPE IF EXISTS entity_type')
    op.execute('DROP TYPE IF EXISTS job_status')
    op.execute('DROP TYPE IF EXISTS metric_data_type')
    op.execute('DROP TYPE IF EXISTS metric_value_status')
    op.execute('DROP TYPE IF EXISTS notification_type')
    op.execute('DROP TYPE IF EXISTS user_role')
    op.execute('DROP TYPE IF EXISTS validation_exception_status')
    op.execute('DROP TYPE IF EXISTS validation_rule_class')
    op.execute('DROP TYPE IF EXISTS validation_severity')
